import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ModalProvider from "@/components/providers/ModalProvider";
import SocketProvider from "@/components/providers/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="discord-theme" >
          <SocketProvider>
            <body className={inter.className}>{children}</body>
            <ModalProvider />
          </SocketProvider>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
